# Generated by Django 4.0.4 on 2022-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
