# Generated by Django 4.0.4 on 2022-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_id_alter_page_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='password',
        ),
        migrations.AddField(
            model_name='page',
            name='hash',
            field=models.CharField(default='lost', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='salt',
            field=models.BinaryField(default=b'lost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
