# Generated by Django 4.0.4 on 2022-04-13 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_page_password_page_hash_page_salt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
