# Generated by Django 4.0.4 on 2022-04-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_page_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='created',
            new_name='createds',
        ),
    ]
